### ISSUE TITLE
CartPole-v1 does not run

### ISSUE THREAD

**Issue by swenner** [lcswillems/torch-rl#14]
python3 -m scripts.train --algo a2c --env CartPole-v1
<pre>
Namespace(algo='a2c', batch_size=256, clip_eps=0.2, discount=0.99, entropy_coef=0.01, env='CartPole-v1', epochs=4, frames=10000000, frames_per_proc=None, gae_lambda=0.95, log_interval=1, lr=0.0007, max_grad_norm=0.5, model=None, no_instr=False, no_mem=False, optim_alpha=0.99, optim_eps=1e-05, procs=16, recurrence=1, save_interval=0, seed=1, tb=False, value_loss_coef=0.5)

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/simon/pytorch-a2c-ppo-git/scripts/train.py", line 106, in <module>
    preprocess_obss = utils.ObssPreprocessor(model_dir, envs[0].observation_space)
  File "/home/simon/pytorch-a2c-ppo-git/utils/format.py", line 40, in __init__
    "image": obs_space.spaces['image'].shape,
AttributeError: 'Box' object has no attribute 'spaces'
</pre>

**Comment by lcswillems** [comment]
Thank you for reporting this bug!
I will try to fix it tonight.

**Comment by lcswillems** [comment]
Is it working now?

**Comment by swenner** [comment]
Unfortunately it still fails:
<pre>
python3 -m scripts.train --algo a2c --env CartPole-v1
/home/simon/pytorch-a2c-ppo-git/scripts/train.py --algo a2c --env CartPole-v1

Namespace(algo='a2c', batch_size=256, clip_eps=0.2, discount=0.99, entropy_coef=0.01, env='CartPole-v1', epochs=4, frames=10000000, frames_per_proc=None, gae_lambda=0.95, instr=False, log_interval=1, lr=0.0007, max_grad_norm=0.5, mem=False, model=None, optim_alpha=0.99, optim_eps=1e-05, procs=16, recurrence=1, save_interval=0, seed=1, tb=False, value_loss_coef=0.5)

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/simon/pytorch-a2c-ppo-git/scripts/train.py", line 105, in <module>
    obs_space, preprocess_obss = utils.get_obss_preprocessor(args.env, envs[0].observation_space, model_dir)
  File "/home/simon/pytorch-a2c-ppo-git/utils/format.py", line 33, in get_obss_preprocessor
    raise "Unknown observation space: " + obs_space
TypeError: Can't convert 'Box' object to str implicitly
</pre>

**Comment by lcswillems** [comment]
This is fixed now. But, anyway, your environment is not handled by default by the code (it is impossible to create a model that works for any kind of observation space). It works out of the box for MiniGrid observation spaces.

Hopefully, the model is easy to modify.

Let me know if I misunderstood something or you think there is a problem in the code.

**Comment by lcswillems** [comment]
I close it. Don't hesitate to open it again if I misunderstood something.
